source "https://rubygems.org"

# Specify your gem's dependencies in osohq-oso.gemspec
gemspec

group :development do
  gem "rake", "~> 12.0", :group => :development
  gem "solargraph", "~> 0.39.8", :group => :development
end

group :test do
  gem "rspec", "~> 3.0", :group => :test
end

gem "ffi", "~> 1.13"
