# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in osohq-oso.gemspec
gemspec

group :development do
  gem 'pry-byebug', '~> 3.9.0'
  gem 'rake', '~> 12.0'
  gem 'solargraph', '~> 0.39.8'
end

group :test do
  gem 'rspec', '~> 3.0'
end

gem 'ffi', '~> 1.13'
