# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "hugo-theme-tailwindcss-starter"
license = "MIT"
licenselink = "https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter/blob/master/LICENSE"
description = "A boilerplate starter theme using Tailwind CSS."
homepage = "https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter"
tags = ["Hugo", "Tailwind CSS", "theme", "starter", "boilerplate"]
features = []
min_version = "0.69"

[author]
  name = "Dirk Olbrich"
  homepage = "https://github.com/dirkolbrich/"
