name: Musl Release
on:
  push:
    branches:
      - "steve/musl"

jobs:
  build_musl_wheels:
    name: Build musl wheels
    runs-on: ubuntu-18.04
    env:
      ENV: CI
    steps:
      - uses: actions/checkout@v2
      - run: docker run --rm --env ENV -v `pwd`:/oso python:3.7-alpine oso/build_musl.sh
      - uses: actions/upload-artifact@v2
        with:
          name: musl-wheel
          path: languages/python/dist/*.whl
