name: Publish SQLAlchemy Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "sqlalchemy_oso version Number"
        required: true
jobs:
  python:
    name: Publish python package to pypi
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "sqlalchemy-v${{ github.event.inputs.version }}"
      - run: |
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/octet-stream" $(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -s https://api.github.com/repos/osohq/oso/releases/tags/sqlalchemy-v${{ github.event.inputs.version }} | jq -r '.assets[] | select(.name == "sqlalchemy-oso-python-${{ github.event.inputs.version }}.zip") | .url') --output sqlalchemy-oso-python-${{ github.event.inputs.version }}.zip
      - run: unzip sqlalchemy-oso-python-${{ github.event.inputs.version }}.zip -d sqlalchemy-oso-python-${{ github.event.inputs.version }}
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.7"
      - run: pip install twine
      - run: twine upload sqlalchemy-oso-python-${{ github.event.inputs.version }}/*.whl --non-interactive
